/**
 * Western Union Payment Service
 * ==============================
 * Integration with Western Union APIs (https://api.westernunion.com)
 *
 * Two distinct API capabilities:
 *   [A] Mass Payments API — OUTBOUND payouts (refunds, commissions, partner payouts).
 *       Supports batches up to 10,000 payments across 130+ currencies.
 *       Auth: OAuth2 client_credentials + mTLS client certificate (.p12).
 *
 *   [B] MTCN Verification — INBOUND payment confirmation.
 *       Customer sends money via WU (agent/online/mobile) → receives MTCN.
 *       They submit the MTCN on checkout → we verify via WU API.
 *
 * For collecting customer payments (the primary use case for a travel agency),
 * the recommended flow is MTCN verification. Mass Payments is used later for
 * refunds and agent commission payouts.
 *
 * NOTE: WU API specifics vary by region/agreement. This module provides a robust
 * production-shaped implementation with a `mock` mode (WU_MODE=mock) for
 * development without real WU credentials or certificates.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const https = require('https');
const crypto = require('crypto');
const axios = require('axios');
const config = require('../config');
const { getStore } = require('../store');

/* ==============================================
 * mTLS HTTP AGENT (client certificate)
 * ============================================== */

/**
 * Build an HTTPS agent with mTLS client certificate.
 * The .p12 / .pfx file must NOT be committed to source control.
 * Store it in a secrets manager or /certs with restricted permissions.
 */
function buildMtlsAgent() {
  const { certPath, certPassphrase } = config.westernUnion;

  if (!certPath || !fs.existsSync(certPath)) {
    throw new Error(
      `WU client certificate not found at ${certPath}. ` +
      'Store the .p12 file outside the repo (e.g. /etc/ssl/wu/ or AWS Secrets Manager).'
    );
  }

  const pfx = fs.readFileSync(certPath);
  const agent = new https.Agent({
    pfx,
    passphrase: certPassphrase || '',
    rejectUnauthorized: true,   // verify WU server cert
    minVersion: 'TLSv1.2'
  });
  return agent;
}

/**
 * Memoized mTLS agent — build once per process.
 */
let _mtlsAgent = null;
function getMtlsAgent() {
  if (!_mtlsAgent) _mtlsAgent = buildMtlsAgent();
  return _mtlsAgent;
}

/* ==============================================
 * OAuth2 TOKEN MANAGEMENT (client_credentials)
 * ============================================== */

let _tokenCache = { token: null, expiresAt: 0 };

/**
 * Acquire a WU Bearer token.
 * In mock mode returns a fake token for development.
 */
async function getWuToken() {
  if (config.westernUnion.mode === 'mock') {
    return 'mock_wu_token_for_development';
  }

  // Return cached token if still valid (5-min safety margin)
  if (_tokenCache.token && _tokenCache.expiresAt > Date.now() + 5 * 60 * 1000) {
    return _tokenCache.token;
  }

  const tokenUrl = `${config.westernUnion.apiBase}/auth/v1/oauth2/token`;

  // WU OAuth2 uses Basic auth (client_id:client_secret) + form-encoded body.
  // Some WU agreements use the cert itself for authentication; we include
  // both Basic and mTLS (cert) for compatibility.
  const basicAuth = Buffer.from(
    `${config.westernUnion.clientId}:${config.westernUnion.clientSecret}`
  ).toString('base64');

  const body = new URLSearchParams({
    grant_type: config.westernUnion.grantType || 'client_credentials',
    scope: config.westernUnion.scope || 'cts-api-branch-payment'
  }).toString();

  const resp = await axios.post(tokenUrl, body, {
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      Authorization: `Basic ${basicAuth}`,
      'User-Agent': 'PascalTravels/1.0'
    },
    httpsAgent: getMtlsAgent()
  });

  const { access_token, expires_in = 3600 } = resp.data;
  _tokenCache = {
    token: access_token,
    expiresAt: Date.now() + expires_in * 1000
  };
  return access_token;
}

/**
 * Standard WU API headers — Bearer token + agent/terminal context.
 */
async function wuHeaders() {
  const token = await getWuToken();
  const wu = config.westernUnion;
  return {
    Authorization: `Bearer ${token}`,
    'Content-Type': 'application/json',
    Accept: 'application/json',
    'User-Agent': 'PascalTravels/1.0',
    'X-AGENT_ID': wu.agentId,
    'X-AGENT_BRANCH': wu.agentBranch,
    'X-AGENT_TERMINAL': wu.agentTerminal,
    'X-AGENT_COUNTRY': wu.agentCountry,
    'X-BANK_ID': wu.bankId
  };
}

/* ==============================================
 * 1. INITIATE WESTERN UNION PAYMENT (checkout)
 * ============================================== */

/**
 * Create a WU payment intent for a booking.
 * Returns instructions + MTCN submission flow.
 *
 * NOTE: MTCN is generated by Western Union AFTER the customer sends money,
 * NOT by the merchant API. So the checkout flow is:
 *   1. We show WU receiver instructions (name, country, amount).
 *   2. Customer sends money via WU agent/online → receives MTCN from WU.
 *   3. Customer submits MTCN back on our site.
 *   4. We verify MTCN via WU API → confirm booking.
 */
async function initiateWesternUnionPayment({ booking, amount, currency = 'KES' }) {
  const store = await getStore();

  const payment = await store.createPayment({
    bookingId: booking.id,
    paymentMethod: 'western_union',
    provider: 'western_union',
    amount,
    currency,
    status: 'AWAITING_CONFIRMATION',
    idempotencyKey: crypto.randomUUID()
  });

  // In live mode, we could pre-create a receiver record via the WU API.
  // For most merchant agreements the receiver is a fixed beneficiary.
  const receiver = {
    name: config.westernUnion.accountNumber || 'Pascal Travels & Tour Ltd',
    country: config.westernUnion.agentCountry || 'KE',
    city: 'Nairobi',
    bankAccount: config.westernUnion.accountNumber || ''
  };

  await store.addTransaction({
    paymentId: payment.id,
    transactionType: 'charge',
    amount,
    currency,
    providerTxnId: '',
    status: 'AWAITING_CONFIRMATION',
    rawResponse: { receiver, amount, currency },
    actor: 'system'
  });

  return {
    payment,
    instructions: {
      paymentId: payment.id,
      receiverName: receiver.name,
      receiverCountry: receiver.country,
      receiverCity: receiver.city,
      amount,
      currency,
      note: 'Send via Western Union to the receiver above, then enter your MTCN (Money Transfer Control Number) to verify your booking.'
    }
  };
}

/* ==============================================
 * 2. VERIFY MTCN (confirm customer payment)
 * ============================================== */

/**
 * Verify an MTCN against Western Union's API.
 * In mock mode, accepts MTCNs matching a known pattern (e.g. starts with 'WU').
 */
async function verifyMTCN({ paymentId, mtcn, senderName, senderCountry, sendAmount, sendCurrency }) {
  const store = await getStore();

  // Validate inputs
  if (!mtcn || !/^[0-9]{10,16}$/.test(String(mtcn).trim())) {
    const err = new Error('Invalid MTCN. A valid MTCN is a 10-16 digit number.');
    err.status = 400;
    throw err;
  }
  mtcn = String(mtcn).trim();

  // Check for existing verification to prevent double-processing
  const existing = await store.getWuVerificationByMTCN(mtcn);
  if (existing) {
    const err = new Error('This MTCN has already been submitted.');
    err.status = 409;
    err.verification = existing;
    throw err;
  }

  // Create the verification record
  const verification = await store.createWuVerification({
    paymentId,
    mtcn,
    senderName,
    senderCountry: senderCountry || '',
    sendAmount: sendAmount || 0,
    sendCurrency: sendCurrency || 'USD',
    payoutCurrency: 'KES'
  });

  // ---- Live verification via WU API ----
  if (config.westernUnion.mode === 'live') {
    try {
      const result = await wuVerifyMTCNLive(mtcn, senderName);
      const updated = await store.updateWuVerification(verification.id, {
        verificationStatus: result.status,       // 'VERIFIED' | 'REJECTED'
        wuApiTxnId: result.wuTxnId,
        verifiedAt: result.verifiedAt || new Date().toISOString(),
        rejectedReason: result.rejectedReason || ''
      });
      await store.addTransaction({
        paymentId,
        transactionType: 'status_change',
        amount: sendAmount || 0,
        currency: sendCurrency || 'USD',
        providerTxnId: mtcn,
        status: result.status === 'VERIFIED' ? 'PAID' : 'FAILED',
        rawResponse: result,
        actor: 'western_union'
      });
      return { verification: { ...verification, ...updated }, ...result };
    } catch (err) {
      await store.updateWuVerification(verification.id, {
        verificationStatus: 'REJECTED',
        rejectedReason: err.message
      });
      throw err;
    }
  }

  // ---- Mock mode: simulate verification ----
  // Accept any valid-format MTCN; mark VERIFIED and payment PAID.
  await new Promise(res => setTimeout(res, 600)); // simulate latency

  const mockResult = {
    status: 'VERIFIED',
    wuTxnId: 'WU-' + mtcn.slice(-8),
    verifiedAt: new Date().toISOString(),
    mock: true
  };

  await store.updateWuVerification(verification.id, {
    verificationStatus: 'VERIFIED',
    wuApiTxnId: mockResult.wuTxnId,
    verifiedAt: mockResult.verifiedAt
  });

  // Mark payment + booking as PAID
  await store.updatePayment(paymentId, {
    status: 'PAID',
    paidAt: new Date().toISOString()
  });
  const payment = await store.getPayment(paymentId);
  await store.updateBooking(payment.bookingId, { status: 'PAID' });

  await store.addTransaction({
    paymentId,
    transactionType: 'charge',
    amount: sendAmount || 0,
    currency: sendCurrency || 'USD',
    providerTxnId: mtcn,
    status: 'PAID',
    rawResponse: { mock: true, mtcn, senderName, senderCountry },
    actor: 'western_union'
  });

  return { verification: { ...verification, ...mockResult }, ...mockResult };
}

/**
 * Live MTCN verification against WU's API.
 * Endpoint path varies by agreement; this uses the standard
 * `GET /api/v1/money-transfer-txn/{mtcn}` style lookup.
 * Override `WU_API_BASE` / endpoint as needed for your region.
 */
async function wuVerifyMTCNLive(mtcn, senderName) {
  const url = `${config.westernUnion.apiBase}/v1/money-transfer-txn/${mtcn}`;
  const resp = await axios.get(url, {
    headers: await wuHeaders(),
    httpsAgent: getMtlsAgent()
  });

  const d = resp.data;

  // WU returns transaction status fields; interpret:
  const status = String(d.status || d.txnStatus || '').toUpperCase();
  const isPaid = ['PAID', 'AVAILABLE', 'COMPLETED', 'SUCCESSFUL'].includes(status) ||
                 d.amountAvailable > 0;

  if (!isPaid) {
    return {
      status: 'REJECTED',
      wuTxnId: d.transactionId || d.txnId || mtcn,
      rejectedReason: `Payment not yet available: ${d.statusMessage || status}`
    };
  }

  return {
    status: 'VERIFIED',
    wuTxnId: d.transactionId || d.txnId || mtcn,
    verifiedAt: new Date().toISOString(),
    raw: d
  };
}

/* ==============================================
 * 3. MASS PAYMENTS API (outbound refunds/payouts)
 * ============================================== */

/**
 * Create a single payout (refund / commission) via WU Mass Payments.
 * Batch API supports up to 10,000 transactions.
 */
async function createPayout({ recipient, amount, currency, reference }) {
  if (config.westernUnion.mode === 'mock') {
    return {
      status: 'SUCCESS',
      mtcn: 'WU' + Math.floor(1000000000 + Math.random() * 8999999999),
      reference,
      mock: true
    };
  }

  const url = `${config.westernUnion.apiBase}/v1/payouts`;
  const payload = {
    paymentMethod: 'BANK',
    reference,
    payoutCurrency: currency,
    recipient: {
      firstName: recipient.firstName,
      lastName: recipient.lastName,
      bankAccount: recipient.bankAccount,
      bankCode: recipient.bankCode || '',
      countryCode: recipient.countryCode || 'KE',
      phone: recipient.phone || ''
    },
    amount: Number(amount).toFixed(2)
  };

  const resp = await axios.post(url, payload, {
    headers: await wuHeaders(),
    httpsAgent: getMtlsAgent()
  });

  return resp.data;
}

/**
 * Batch payout — up to 10,000 transactions.
 */
async function createBatchPayout({ payouts }) {
  if (config.westernUnion.mode === 'mock') {
    return {
      batchId: 'BATCH-' + Date.now(),
      status: 'SUCCESS',
      submitted: payouts.length,
      mock: true
    };
  }

  const url = `${config.westernUnion.apiBase}/v1/batch-payouts`;
  const resp = await axios.post(url, { payouts }, {
    headers: await wuHeaders(),
    httpsAgent: getMtlsAgent()
  });
  return resp.data;
}

/* ==============================================
 * 4. STATUS POLLING (when webhooks unavailable)
 * ============================================== */

/**
 * Poll the status of a WU payment by MTCN.
 */
async function checkWuStatus(paymentId) {
  const store = await getStore();
  const payment = await store.getPayment(paymentId);
  if (!payment || payment.paymentMethod !== 'western_union') {
    const err = new Error('WU payment not found');
    err.status = 404;
    throw err;
  }

  const verification = payment.providerRef
    ? await store.getWuVerificationByMTCN(payment.providerRef)
    : null;

  return {
    payment: { ...payment },
    verification,
    status: payment.status
  };
}

/* ==============================================
 * 5. WEBHOOK HANDLER
 * ============================================== */

/**
 * Process an incoming Western Union webhook.
 * WU webhook payloads vary by agreement; handle both common shapes.
 */
async function handleWesternUnionWebhook({ headers, body }) {
  const store = await getStore();

  const signatureValid = verifyWuWebhookSignature(headers, body);
  const eventId = body.eventId || body.event_id || body.id ||
                  body.transactionId || body.mtcn || crypto.randomUUID();

  const existing = await store.getWebhookEventByEventId(String(eventId));
  if (existing && existing.processed) {
    return { processed: false, duplicate: true, eventId };
  }

  const event = await store.createWebhookEvent({
    provider: 'western_union',
    eventType: body.eventType || body.type || body.status || 'status_update',
    eventId: String(eventId),
    payload: body,
    signatureOk: signatureValid
  });

  if (!signatureValid) {
    return { processed: false, signatureInvalid: true, eventId };
  }

  // Locate the payment by MTCN
  const mtcn = body.mtcn || body.moneyTransferControlNumber || body.transferNumber || '';
  let payment = null;
  if (mtcn) {
    const verification = await store.getWuVerificationByMTCN(String(mtcn).trim());
    if (verification) payment = await store.getPayment(verification.paymentId);
  }

  if (!payment) {
    // Try by providerRef
    payment = await store.getPaymentByProviderRef(String(mtcn));
  }

  if (!payment) {
    return { processed: false, paymentNotFound: true, eventId };
  }

  // Determine status
  const wuStatus = String(body.status || body.txnStatus || body.statusCode || '').toUpperCase();
  let mapped = payment.status;
  if (['PAID', 'AVAILABLE', 'COMPLETED', 'SUCCESSFUL', 'PAYOUT_COMPLETED'].includes(wuStatus)) {
    mapped = 'PAID';
  } else if (['FAILED', 'REJECTED', 'CANCELLED', 'CANCELED', 'REVERSED'].includes(wuStatus)) {
    mapped = 'FAILED';
  } else if (['PENDING', 'PROCESSING', 'IN_PROGRESS'].includes(wuStatus)) {
    mapped = 'PROCESSING';
  }

  if (mapped !== payment.status) {
    const updates = { status: mapped };
    if (mapped === 'PAID') updates.paidAt = new Date().toISOString();
    await store.updatePayment(payment.id, updates);

    await store.addTransaction({
      paymentId: payment.id,
      transactionType: 'status_change',
      amount: payment.amount,
      currency: payment.currency,
      providerTxnId: String(mtcn),
      status: mapped,
      rawResponse: body,
      actor: 'webhook:western_union'
    });

    if (mapped === 'PAID') {
      await store.updateBooking(payment.bookingId, { status: 'PAID' });
    }
  }

  await store.markWebhookProcessed(event.id);
  return { processed: true, paymentId: payment.id, status: mapped, eventId };
}

/**
 * Verify WU webhook signature (HMAC-SHA256 of raw body, hex or base64).
 * Header names vary; configure via WU_WEBHOOK_SECRET.
 */
function verifyWuWebhookSignature(headers, body) {
  const secret = config.westernUnion.webhookSecret;
  if (!secret) return true; // dev mode

  const signature =
    headers['x-wu-signature'] || headers['x-signature'] ||
    headers['signature'] || headers['x-webhook-signature'];
  if (!signature) return false;

  const rawBody = typeof body === 'string' ? body : JSON.stringify(body);
  const hmacHex = crypto.createHmac('sha256', secret).update(rawBody).digest('hex');

  const provided = signature.startsWith('sha256=') ? signature.slice(7) : signature;
  const a = Buffer.from(hmacHex);
  const b = Buffer.from(provided);
  if (a.length !== b.length) return false;
  return crypto.timingSafeEqual(a, b);
}

/* ==============================================
 * 6. ERROR HANDLING / SAMPLE PAYLOADS
 * ============================================== */

/**
 * Normalize WU API errors into friendly messages.
 */
function wuErrorHandler(err) {
  if (err.response) {
    const d = err.response.data;
    return new Error(
      `Western Union error ${err.response.status}: ${d.errorDescription || d.message || d.error || 'Unknown'}`
    );
  }
  if (err.code === 'CERT_HAS_EXPIRED' || err.code === 'DEPTH_ZERO_SELF_SIGNED_CERT') {
    return new Error('Western Union certificate error. Check that the mTLS client certificate is valid and not expired.');
  }
  return new Error(`Western Union request failed: ${err.message}`);
}

const SAMPLE_PAYLOADS = {
  wuMTCNVerificationRequest: {
    mtcn: '1284947565123',
    senderName: 'Jane Wanjiru Kamau',
    senderCountry: 'KE',
    sendAmount: 1500,
    sendCurrency: 'USD'
  },
  wuMTCNVerificationResponse: {
    status: 'VERIFIED',
    wuTxnId: 'WU-84567512',
    verifiedAt: '2026-01-15T10:35:00Z',
    sendAmount: 1500.00,
    sendCurrency: 'USD',
    payoutAmount: 194250.00,
    payoutCurrency: 'KES'
  },
  wuBatchPayoutRequest: {
    batchId: 'REFUND-BATCH-001',
    payouts: [
      {
        recipient: { firstName: 'Jane', lastName: 'Kamau', bankAccount: '0101234567890', countryCode: 'KE' },
        amount: 5000.00,
        currency: 'KES',
        reference: 'REF-1001'
      }
    ]
  }
};

module.exports = {
  buildMtlsAgent,
  getWuToken,
  initiateWesternUnionPayment,
  verifyMTCN,
  createPayout,
  createBatchPayout,
  checkWuStatus,
  handleWesternUnionWebhook,
  verifyWuWebhookSignature,
  wuErrorHandler,
  SAMPLE_PAYLOADS
};

